spring:
  datasource:
#    url: jdbc:mysql://bxdmysql.freenat.win:53306/sms_gateway_db?useSSL=false
    url: jdbc:mysql://172.16.11.17:3306/sms_gateway_db?useSSL=false
    username: root
    password: Bxd@12345
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 172.16.11.17
#    host: bxdredis.freenat.win
    # Redis服务器连接端口
    port: 6379
#    port: 56379
    # Redis服务器连接密码（默认为空）
    password: Bxd12345
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

server:
  port: 5022

logging:
  level:
   com: debug